version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
  sayHello:
    jobs:
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
