export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQUES_ROBOTS_PENDING = 'REQUES_ROBOTS_PENDING'

export const REQUES_ROBOTS_SUCCESS = 'REQUES_ROBOTS_SUCCESS'

export const REQUES_ROBOTS_FAILED = 'REQUES_ROBOTS_FAILED'
